#!/bin/sh
# Pre-commit hook for TiyatroFlix project
# Copy or symlink this file to .git/hooks/pre-commit to enable pre-commit linting

# Change to frontend directory and run lint-staged
cd frontend && npx lint-staged  && cd ..
cd backend && dotnet format && cd ..

# Exit with the status of lint-staged
exit $?